### PR TITLE
Use Binary builder when possible

### PR DESCRIPTION
**Pull request by ericphanson**
This code uses BinaryBuilder to generate the binaries when possible, falling back to the PATH option otherwise. I wasn't able to test this on Windows though-- could you try? What should happen is that when you `] build` it should give a warning, but finish building. Then when you use it, it should search for `sdpa_gmp` in your PATH variable, and work if it's on the path.

On linux and MacOS it should install the binary builder version of SDPA-GMP and just work.

If this works ok, then we're in business, testing-wise, because we can use Travis for testing SDPA-GMP code (now that it can easily install the binaries). So we can add some tests to Convex.jl, and also run the tests for this package on travis (without it always just failing due to no binaries).

### CODE REVIEW

**Comment by ericphanson** [comment]
We could use an environmental variable also, as is done for SCS: https://github.com/JuliaOpt/SCS.jl/blob/master/deps/build.jl. That would let you use a custom binary even on MacOS or Linux (I think currently this PR forces you to binary builder if it's available). I think that's probably a more reasonable solution.

**Comment by ericphanson** [comment]
Notes from our discussion on BB -> WSL -> Windows julia. These would be the instructions we give the user for installing SDPA_GMP on windows:

1. Install WSL
2. Go to `https://github.com/ericphanson/SDPA_GMP_Builder/releases`, copy the link for the latest `x86_64-linux-gnu.tar.gz` file
2. In WSL: do something like
```bash
wget link
tar -xf SDPABuilder.v7.1.3-patched.x86_64-linux-gnu.tar.gz
mv SDPABuilder.v7.1.3-patched.x86_64-linux-gnu.tar.gz/sdpa_gmp /usr/bin/sdpa_gmp
```
where `link` is the latest `x86_64-linux-gnu.tar.gz` file
where we have to update the link to the latest BB version when we release it.
3. `]build SDPA_GMP` from Windows (uses `wsl sdpa_gmp`)

For us:

In `build.jl`:
Check: is `JL_SDPA_GMP` set?
* yes, `JL_SDPA_GMP=“/files/sdpa_gmp”`. Check if this is a binary, use it or error
* no: mac / linux, use BB. Windows: try WSL. If it works, set `WSL=true`.

In `sdpa_binary_call` if `WSL==true` then use `wslpath` to translate paths before sending them to the binary

**Comment by ericphanson** [comment]
It seems naming the version as “v7.1.3-patch-2” in the BB repo messes up BB in build.jl. We’ll need to name the version something else. I don’t want to call it “v7.1.4” though since SDPA-GMP itself may update that version number. We could just call it “v1.0.2” where “v1” corresponds to “v7.1.3” and then the “.0.2” is for the two printing changes since then.

**Comment by ericphanson** [comment]
Ok, I fixed the version number issue and rewrote the BB support. However, when I try to use the sdpa_gmp binary on my windows computer, it segfaults. So I'm not quite sure what to do. I suspect my `ExecutableProduct` in the WSL case isn't correct (in the build.jl file), but I can't test it until I get the binary working on WSL here (... which may never happen).

Can you test this PR @JiazhengZhu? What we want to happen is:

- [x]  On MacOS
- [x] or Linux, 
- [ ] or within WSL itself
- [ ] or Windows outside of WSL, but with a `sdpa_gmp` binary on the WSL path, just `]add https://github.com/ericphanson/SDPA_GMP.jl#BinaryBuilder` in a fresh environment gives a working version without having to do anything with the paths
- [ ]  If you set the `JULIA_SDPA_GMP_PATH` environmental variable to a folder containing an sdpa_gmp binary and then build, then it uses that binary. (described in the README in this PR).

I've checked the first two-- can you check the remaining three?

I made some changes to simplify some of the code and change a few things, and also to complicate some of the code (for WSL handling), and I'd like to get this merged first thing so we can test on Travis, and so the code here doesn't get stale (i.e. you make other changes to the main repo that conflicts with these, and we have to sort it out). So I'd prefer this to be the first priority, in terms of code changes to SDPA-GMP.

**Comment by JiazhengZhu** [comment]
Indeed I have the same issue following the instructions on readme. But curiously enough if I unpack the binary using file explorer and `cd` to the Windows folder the segmentation fault does not appear. I'm not too sure but would it be safer to instruct Travis to build the binary on windows under WSL and pack the Linux binary as its release for Windows? (Think Travis has [WSL installed](https://docs.travis-ci.com/user/reference/windows/). ) Then on Windows we would just run a binary call like `wsl /mnt/c/users/name/.julia/packages/SDPA_GMP/...`?

**Comment by JiazhengZhu** [comment]
Also if I manually get the `sdpa_gmp` binary into PATH, (changing the empty string [here](https://github.com/ericphanson/SDPA_GMP.jl/blob/a9b803ba603d1dd32a994a4bc8cb2a5a83be8f4c/deps/build.jl#L58) to `Prefix("")` so that it doesn't error)  then I have
```
 Error: Error building `SDPA_GMP`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:794
│ [ Info: SDPA-GMP does not directly support Windows. See the SDPA_GMP.jl readme for instructions on setting up SDPA-GMP via Windows subsystem for linux.
│ [ Info: Windows subsystem for Linux detected. Trying `sdpa_gmp` there.
│ [ Info: Attempt to use `sdpa_gmp` succeeded. Using `sdpa_gmp` via WSL.
│ ERROR: LoadError: ExecutableProduct("C:\\Users\\zhuji\\.julia\\packages\\SDPA_GMP\\jCfmr\\deps\\usr\\bin\\sdpa_gmp", :sdpa_gmp, "Prefix(C:\\Users\\zhuji\\.julia\\packages\\SDPA_GMP\\jCfmr\\deps\\usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #write_deps_file#156(::Bool, ::Function, ::String, ::Array{ExecutableProduct,1}) at C:\Users\zhuji\.julia\packages\BinaryProvider\TcAwt\src\Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{ExecutableProduct,1}) at .\none:0
│  [4] top-level scope at none:0
│  [5] include at .\boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:403
│  [9] top-level scope at none:0
│ in expression starting at C:\Users\zhuji\.julia\packages\SDPA_GMP\jCfmr\deps\build.jl:77
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
```
It appears that the BinaryBuilder is still trying to do something with the downloaded binary?

**Comment by ericphanson** [comment]
> Indeed I have the same issue following the instructions on readme. But curiously enough if I unpack the binary using file explorer and `cd` to the Windows folder the segmentation fault does not appear. I'm not too sure but would it be safer to instruct Travis to build the binary on windows under WSL and pack the Linux binary as its release for Windows? (Think Travis has [WSL installed](https://docs.travis-ci.com/user/reference/windows/). ) Then on Windows we would just run a binary call like `wsl /mnt/c/users/name/.julia/packages/SDPA_GMP/...`?

Ah, good investigating! That's very promising, because it might mean we can have a 0-effort install even on Windows, as long as the user has WSL installed. Maybe in the `build.jl`, we can detect WSL, then download the linux binary and extract it. I don't think we want to use windows on Travis here, because the build is happening in the binarybuilder environment which wants to run on Linux.

> Also if I manually get the `sdpa_gmp` binary into PATH, (changing the empty string [here](https://github.com/ericphanson/SDPA_GMP.jl/blob/a9b803ba603d1dd32a994a4bc8cb2a5a83be8f4c/deps/build.jl#L58) to `Prefix("")` so that it doesn't error) then I have
> 
> ```
>  Error: Error building `SDPA_GMP`:
> │ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
> │ └ @ Base.Filesystem file.jl:794
> │ [ Info: SDPA-GMP does not directly support Windows. See the SDPA_GMP.jl readme for instructions on setting up SDPA-GMP via Windows subsystem for linux.
> │ [ Info: Windows subsystem for Linux detected. Trying `sdpa_gmp` there.
> │ [ Info: Attempt to use `sdpa_gmp` succeeded. Using `sdpa_gmp` via WSL.
> │ ERROR: LoadError: ExecutableProduct("C:\\Users\\zhuji\\.julia\\packages\\SDPA_GMP\\jCfmr\\deps\\usr\\bin\\sdpa_gmp", :sdpa_gmp, "Prefix(C:\\Users\\zhuji\\.julia\\packages\\SDPA_GMP\\jCfmr\\deps\\usr)") is not satisfied, cannot generate deps.jl!
> │ Stacktrace:
> │  [1] error(::String) at .\error.jl:33
> │  [2] #write_deps_file#156(::Bool, ::Function, ::String, ::Array{ExecutableProduct,1}) at C:\Users\zhuji\.julia\packages\BinaryProvider\TcAwt\src\Products.jl:414
> │  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{ExecutableProduct,1}) at .\none:0
> │  [4] top-level scope at none:0
> │  [5] include at .\boot.jl:326 [inlined]
> │  [6] include_relative(::Module, ::String) at .\loading.jl:1038
> │  [7] include(::Module, ::String) at .\sysimg.jl:29
> │  [8] include(::String) at .\client.jl:403
> │  [9] top-level scope at none:0
> │ in expression starting at C:\Users\zhuji\.julia\packages\SDPA_GMP\jCfmr\deps\build.jl:77
> └ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
> ```
> 
> It appears that the BinaryBuilder is still trying to do something with the downloaded binary?

Ah, I missed the `Prefix` bit. Yes, BinaryBuilder does some checks; for ExecutableProducts it appears to be this:
https://github.com/JuliaPackaging/BinaryProvider.jl/blob/6779f5408a5ec0047ed581a3ffa02edcf044be00/src/Products.jl#L249-L257

Maybe the long term solution is to add a WSL product or something like that to BinaryBuilder / BinaryProvider, which does different checks. In the meantime though, on WSL we can just skip out of the BP checks by not doing `write_deps_file`, and instead writing our own file. We already do that a bit on this branch by appending `const has_WSL = $has_WSL`. Instead, we would just write the whole file ourselves (only on Windows), which would just be that line + setting `sdpa_gmp` to the correct path.

**Comment by ericphanson** [comment]
Actually, I'm not sure BB/BP would want to spend much time adding a WSL product or such, because I think usually one wants to make a shared library to use from Julia that you `dlopen`, instead of just a binary that you send commands to. And I imagine the `dlopen` case won't work to open a linux binary on windows. So probably we are in a bit of an unusual case here, and writing our own deps file is likely the way to go.

**Comment by ericphanson** [comment]
Actually, maybe on Windows we should just call it a file product! Then BB will extract it for us and all that, but it just checks that it exists.

**Comment by ericphanson** [comment]
Ok, I'm not at my windows computer so I can't test this, but I pushed a commit with the above ideas. Can you try it out?

**Comment by JiazhengZhu** [comment]
This should build fine after two changes: in `build.jl` the prefix at line 5 should be `/usr/bin` and in `install` at line 73 we need to pass `ignore_platform = true`.

Manually setting `has_WSL = true` in deps.jl is also necessary: is this meant to be this way? But this time the process died with exit code 139, which means segfault...

**Comment by ericphanson** [comment]
> This should build fine after two changes: in `build.jl` the prefix at line 5 should be `/usr/bin` and in `install` at line 73 we need to pass `ignore_platform = true`.
> 
> Manually setting `has_WSL = true` in deps.jl is also necessary: is this meant to be this way? But this time the process died with exit code 139, which means segfault...

Oops, I just forgot to set `has_WSL = true` in the WSL case. I added that and the `ignore_platform`. But I'm not sure about the path or the segfault-- I'll be at the coffee meeting this afternoon, maybe you can show me after if you're around?

**Comment by JiazhengZhu** [comment]
Sure see you soon :)

**Comment by ericphanson** [comment]
Ok, I added the WSL binary you built and update the `build.jl` file to try to use it. Merge if it works!

**Comment by ericphanson** [comment]
I rebased on top of master, meaning this branch is now update with the changes in master. In particular, that means the Travis run that just started should finally pass :).

**Comment by ericphanson** [comment]
Nope, missing some dependencies. I'll push a fix in a minute, as well as a couple small other changes.

**Comment by JiazhengZhu** [comment]
Also I think the `download_verify` call should be
`BinaryProvider.download_verify("https://github.com/ericphanson/SDPA_GMP_Builder/tree/master/deps/sdpa_gmp_wsl","ba6e7f75f75435d17c255a24639136369e159145e39a9dc785a04a3706e7c58e", joinpath(prefix.path,"sdpa_gmp"); verbose=verbose)`
since there seems to be a new hash and `url` etc are not actually keyword arguments. 

Also line 66 could be something like `if dl_info !== nothing && ((unsatisfied || !isinstalled(dl_info...; prefix = prefix))) && !custom_library` so that we won't have error when iterating through `nothing`.

**Comment by ericphanson** [comment]
Ah, thanks, I'll change that. I'm getting some errors when running the tests locally. Some of it was due to dependencies, which I think I fixed in the commit I just pushed, but some of it is things like
```julia
Partial trace: Error During Test at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/test/Convex/test_sdp.jl:167
  Got exception outside of a @test
  AssertionError: MOI.is_empty(optimizer)
  Stacktrace:
   [1] MathOptInterface.Utilities.CachingOptimizer(::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{BigFloat}}, ::SDPA_GMP.Optimizer{BigFloat}) at /Users/eh540/.julia/packages/MathOpt
```

**Comment by ericphanson** [comment]
Windows failed because I had the wrong link; MacOS failed because some presolve tests failed (https://travis-ci.com/ericphanson/SDPA_GMP.jl/jobs/231197008), and Linux failed from the same errors I got about empty optimizers (https://travis-ci.com/ericphanson/SDPA_GMP.jl/jobs/231197010).

I think for the empty optimizer thing, we might need to pass a fresh optimizer to every test. So instead of setting `solver` to be the optimizer itself, we set `solver = () -> SDPA_GMP.Optimizer...`, and call `solver()` to get a fresh optimizer.

For the presolve, I'm not sure. As we talked about, what we want to do here is not numerically stable, and this is likely a reflection of that. Probably we should turn off presolve by default, and instead suggest turning it on if you get cholesky miss conditions, and mention that it isn't stable.

Regarding the tests, we should find a way to make them more robust. Try to see exactly what goes wrong in the failing condition, and maybe we can find a way to make the test examples we use there less likely to fail.

Regarding this branch: if Windows CI sucessfully loads sdpa_gmp via WSL and solves some problems, I say we merge this branch. If there's still BB problems then let's fix them on the branch, but once BB works, let's fix the tests on master.

**Comment by JiazhengZhu** [comment]
When using `cd` in windows we have to make sure it's using the normal windows path, not WSL path though... Fixing this should make the tests run but we also have to exclude "solve_affine_equalto" test under MOI unit test section. This is due to the returned value of SDPA-GMP being too large for Float64 and the results underflow.

**Comment by ericphanson** [comment]
> When using `cd` in windows we have to make sure it's using the normal windows path, not WSL path though... 

Just fixed this! (I think...)

>Fixing this should make the tests run but we also have to exclude "solve_affine_equalto" test under MOI unit test section. This is due to the returned value of SDPA-GMP being too large for Float64 and the results underflow.

Hm strange, does it work on other solvers?

**Comment by ericphanson** [comment]
Ok, now we get
```
  failed process: Process(`wsl sdpa_gmp -ds /mnt/c/users/travis/appdata/local/temp/jl_1491.tmp/input.dat-s -o /mnt/c/users/travis/appdata/local/temp/jl_1491.tmp/output.dat -p /mnt/c/users/travis/build/ericphanson/sdpa_gmp.jl/deps/param.sdpa`, ProcessExited(4294967295)) [4294967295]
```
on Windows on Travis. Any idea?

**Comment by ericphanson** [comment]
I fixed the convex tests (by getting a fresh optimizer each time), and turned off presolve by default. I also built QD (https://github.com/ericphanson/QD_Builder) and added SDPA-QD and SDPA-DD to our builder https://github.com/ericphanson/SDPA_GMP_Builder, and to SDPA-GMP. All three solvers can solve a trivial problem :). We should think if we want to rename the package or not.

BB-stuff left: Windows via WSL (Travis got that process error), and running *within* WSL, which I don't think we've tested at all.

Test stuff left: things in the release-checklist  (I updated it).

**Comment by ericphanson** [comment]
Huh, no idea why Travis is failing; it worked locally! Will have to figure it out another time.

**Comment by ericphanson** [comment]
> Huh, no idea why Travis is failing; it worked locally! Will have to figure it out another time.

Now I know why Travis failed; the build.jl wasn't right for trying to install both QD and the SDPA binaries. (I put both bits in the same downloadinfo, which means it chooses to *either* install QD or SDPA...). I don't actually know why it worked locally though.

I reorganized the build.jl file to make the structure relatively simple, and fix these problems. I *think* QD and DD are now working (on linux and macos). So we're back to assorted test failures (see e.g. https://travis-ci.com/ericphanson/SDPA_GMP.jl/jobs/231428494) and WSL not working.

**Comment by JiazhengZhu** [comment]
For the failed tests I think we must use presolve... I'm not too sure why WSL is failing and the error code is just 2^32-1?

**Comment by ericphanson** [comment]
Ah, I had put in presolve for the Convex tests but I forgot it for the MOI tests. Hm... maybe we should put it back to be the default if we need it for so many of the tests.

I changed the presolve tests to use rationals instead of big floats, and they seem to work. I constructed the matrices to have elements of type `Rational{BigInt}` instead of rationalizing big floats; computation with `Rational{BigInt}` should be exact, whereas rationalizing could introduce errors as you mentioned in https://github.com/ericphanson/SDPA_GMP.jl/issues/4#issuecomment-528418922.

**Comment by ericphanson** [comment]
I think I'll merge this; I'm not sure what's going on with WSL but it no longer seems helpful to have development in two separate branches, especially since you can use the environmental variables to set the default binary to anything (so BB isn't in the way of dev and testing).

**Comment by JiazhengZhu** [comment]
Sure will do that now.

**Pull request merged**
