### PR TITLE
Add plain SDPA for comparisons

### PR DESCRIPTION
**Pull request by ericphanson**
This branch adds plain `Float64` SDPA so that it can be used in the exact same way as SDPA-{GMP,DD,QD}. Of course, SDPA.jl technically does this better by wrapping the C++-library so one can communicate with SDPA without going through file writing and reading. However, under certain circumstances one might want to compare the performance of high precision variants of SDPA vs the original SDPA in an apples-to-apples way, without also comparing the performance of file IO. This also allows such comparisons to use the presolve with plain SDPA (which we could upstream to SDPA.jl as well, but that's sort of a separate consideration).

I got the build sorted out (avoiding the CxxWrap'd version so we don't have to add dependencies or complications), but the tests fail due to a parsing issue:
```julia
julia> include("../test/high_precision_test.jl")
[ Info: Recompiling stale cache file /Users/eh540/.julia/compiled/v1.1/SDPA_GMP/Lnqob.ji for SDPA_GMP [bfe18334-aefd-11e9-1109-4bf2b15a5b91]
┌ Info: `using SDPA_GMP`
└   time = 7.014501777
High precision test: Error During Test at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/test/high_precision_test.jl:6
  Got exception outside of a @test
  ArgumentError: cannot parse "+0e" as BigFloat
  Stacktrace:
   [1] _parse_failure(::Type, ::SubString{String}, ::Int64, ::Int64) at ./parse.jl:370 (repeats 2 times)
   [2] #tryparse_internal#349 at ./parse.jl:366 [inlined]
   [3] tryparse_internal at ./parse.jl:364 [inlined]
   [4] #parse#350 at ./parse.jl:376 [inlined]
   [5] parse at ./parse.jl:376 [inlined]
   [6] _broadcast_getindex_evalf at ./broadcast.jl:578 [inlined]
   [7] _broadcast_getindex at ./broadcast.jl:561 [inlined]
   [8] getindex at ./broadcast.jl:511 [inlined]
   [9] macro expansion at ./broadcast.jl:843 [inlined]
   [10] macro expansion at ./simdloop.jl:73 [inlined]
   [11] copyto! at ./broadcast.jl:842 [inlined]
   [12] copyto! at ./broadcast.jl:797 [inlined]
   [13] copy at ./broadcast.jl:773 [inlined]
   [14] materialize at ./broadcast.jl:753 [inlined]
   [15] (::getfield(SDPA_GMP, Symbol("##12#18")){BigFloat,SDPA_GMP.Optimizer{BigFloat},getfield(SDPA_GMP, Symbol("#getnextline#15")){String},getfield(SDPA_GMP, Symbol("#remove_brackets!#17"))})(::IOStream) at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/src/file_io.jl:73
   [16] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(SDPA_GMP, Symbol("##12#18")){BigFloat,SDPA_GMP.Optimizer{BigFloat},getfield(SDPA_GMP, Symbol("#getnextline#15")){String},getfield(SDPA_GMP, Symbol("#remove_brackets!#17"))}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:375
   [17] open at ./iostream.jl:373 [inlined]
   [18] read_results!(::SDPA_GMP.Optimizer{BigFloat}, ::String, ::Array{Int64,1}) at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/src/file_io.jl:39
   [19] #sdpa_gmp_binary_solve!#29(::Cmd, ::Array{Int64,1}, ::Function, ::SDPA_GMP.Optimizer{BigFloat}, ::String, ::String) at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/src/binary_call.jl:27
   [20] (::getfield(SDPA_GMP, Symbol("#kw##sdpa_gmp_binary_solve!")))(::NamedTuple{(:redundant_entries,),Tuple{Array{Int64,1}}}, ::typeof(SDPA_GMP.sdpa_gmp_binary_solve!), ::SDPA_GMP.Optimizer{BigFloat}, ::String, ::String) at ./none:0
   [21] optimize!(::SDPA_GMP.Optimizer{BigFloat}) at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/src/MOI_wrapper.jl:312
   [22] optimize!(::MathOptInterface.Utilities.CachingOptimizer{SDPA_GMP.Optimizer{BigFloat},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{BigFloat}}}) at /Users/eh540/.julia/packages/MathOptInterface/016Ol/src/Utilities/cachingoptimizer.jl:178
   [23] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SDPA_GMP.Optimizer{BigFloat},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{BigFloat}}}}) at /Users/eh540/.julia/packages/MathOptInterface/016Ol/src/Bridges/bridge_optimizer.jl:139
   [24] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.Model{BigFloat}}) at /Users/eh540/.julia/packages/MathOptInterface/016Ol/src/Utilities/cachingoptimizer.jl:178
   [25] #solve!#5(::Bool, ::Bool, ::Function, ::Problem{BigFloat}, ::SDPA_GMP.Optimizer{BigFloat}) at /Users/eh540/.julia/packages/Convex/28HAH/src/moi_model.jl:191
   [26] solve!(::Problem{BigFloat}, ::SDPA_GMP.Optimizer{BigFloat}) at /Users/eh540/.julia/packages/Convex/28HAH/src/moi_model.jl:178
   [27] top-level scope at util.jl:213
   [28] top-level scope at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/test/high_precision_test.jl:11
   [29] top-level scope at /Applications/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [30] top-level scope at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/test/high_precision_test.jl:7
   [31] include_relative(::Module, ::String) at /Applications/Julia-1.1.app/Contents/Resources/julia/lib/julia/sys.dylib:?
   [32] include(::Module, ::String) at ./sysimg.jl:29
   [33] include(::String) at ./client.jl:403
   [34] top-level scope at none:0
   [35] eval(::Module, ::Any) at /Applications/Julia-1.1.app/Contents/Resources/julia/lib/julia/sys.dylib:?
   [36] eval_user_input(::Any, ::REPL.REPLBackend) at /Applications/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
   [37] run_backend(::REPL.REPLBackend) at /Users/eh540/.julia/packages/Revise/agmgx/src/Revise.jl:949
   [38] (::getfield(Revise, Symbol("##75#77")){REPL.REPLBackend})() at ./task.jl:259
Test Summary:       | Error  Total
High precision test |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/eh540/Dropbox (Personal)/LinkedFolders/Julia/dev/SDPA_GMP/test/high_precision_test.jl:6
```

It sounds like SDPA is outputting something with a slightly different numeric than SDPA-GMP has been, but a fix here would hopefully help make our file IO more robust in general. Can you try to see if you can fix the parsing?

### CODE REVIEW

**Comment by ericphanson** [comment]
Just to say, I think next time it would be better to keep this in a branch until the problems are fixed rather than merging it right away (since now tests don't pass on master). It should be just as easy to develop on this branch (just checkout `SDPA-plain` and work on there; any commits you push will update this PR), and that way master can be kept in a good state. I guess it doesn't really matter much in this particular situation, but it's a good practice to have.

**Comment by JiazhengZhu** [comment]
Sure will pay more attention next time. Sorry to keep bothering you though, but on Travis and my local copy I'm seeing the same error about the missing shared library again? 
The parsing error is due to the plain version getting wrong lines from the gmp version param file. I have just fixed this by pointing it to its own params file.

**Comment by ericphanson** [comment]
Ah ok, glad you found a fix! Huh, very strange, it looks like it passes on MacOS and fails on linux with the shared library error. I don't know how I could've fixed it just for MacOS, but I guess that's what I did. I will try to take a look tonight but may not get to it, in which case it might be a few days. In that case you can just comment out the test and avoid `variant=:plain` for a bit.

**Comment by ericphanson** [comment]
Just a brief update on this: the first problem is that SDPA isn't finding `libsdpa` even though it's there in `deps/usr/lib`. This is fixed by following FFMPEG.jl and adding
```julia

const libpath = joinpath(@__DIR__, "..", "deps", "usr", "lib")

if Sys.iswindows()
    const execenv = ("PATH" => string(libpath, ";", Sys.BINDIR))
elseif Sys.isapple()
    const execenv = ("DYLD_LIBRARY_PATH" => libpath)
else
    # const execenv = ("LD_LIBRARY_PATH" => string(libpath, ":", ENV["LD_LIBRARY_PATH"]))
    const execenv = ("LD_LIBRARY_PATH" => libpath)
end
```
to set an `environment`, and then using it during `run` via
```julia
withenv(execenv) do
    run(pipeline(`$(m.binary_path) $arg`, stdout = m.silent ? devnull : stdout))
end
```
That gets me to the next error (at least on the linux computer I'm using), which is an error that it can't find `libgfortran`. I'm not sure how SDPA.jl handles this (I must assume somehow CxxWrap is helping here), but if I run `build_tarballs.jl` from SDPABuilder, it gives me the warning that

```julia
Warning: /store/CCIMI/eh540/.julia/dev/SDPABuilder/build/i686-linux-gnu/44rLJ5wZ/destdir/bin/sdpa links to libgfortran!  This causes incompatibilities across major versions of GCC.  To remedy this, you must build a tarball for each major version of GCC.  To do this, immediately after your `products` definition in your `build_tarballs.jl` file, add the line:

    products = expand_gcc_versions(products)
```
(apparently `products` here is meant to be `platforms`). So now I'm trying to build with that option. We might end up with a forked SDPABuilder with the C++ wrapper stuff tossed out to get this to work.

**Comment by ericphanson** [comment]
Ok, I think I fixed it! It turns out that instead of using `Base.withenv`, there's a `BinaryProvider.withenv` where you can pass a `Prefix`, and somehow that works.

The real test I guess will be if CI passes: https://travis-ci.com/ericphanson/SDPA_GMP.jl/builds/126305125

**Comment by JiazhengZhu** [comment]
Many thanks for the fix! Everything's looking good on Travis now.

**Pull request merged**
